#!/command/with-contenv sh
# create missing cache directories and exit
/usr/sbin/squid -Nz


tail -F /var/log/squid/access.log 2>/dev/null &
tail -F /var/log/squid/error.log 2>/dev/null &
tail -F /var/log/squid/store.log 2>/dev/null &
tail -F /var/log/squid/cache.log 2>/dev/null &

access_log daemon:/var/log/squid/access.log squid